/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanager;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maciej
 */
public class bazacreator extends javax.swing.JFrame {

    int index;

    /**
     * Creates new form bazacreator
     */
    public bazacreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logf = new javax.swing.JTextField();
        hasf = new javax.swing.JTextField();
        serverF = new javax.swing.JTextField();
        bazaf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        portF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxIndex = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 330));
        setMinimumSize(new java.awt.Dimension(410, 330));
        setPreferredSize(new java.awt.Dimension(410, 330));
        getContentPane().setLayout(null);

        logf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logfActionPerformed(evt);
            }
        });
        getContentPane().add(logf);
        logf.setBounds(210, 90, 80, 30);
        getContentPane().add(hasf);
        hasf.setBounds(210, 120, 80, 30);
        getContentPane().add(serverF);
        serverF.setBounds(210, 150, 140, 30);
        getContentPane().add(bazaf);
        bazaf.setBounds(210, 180, 80, 30);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 90, 40, 14);

        jLabel2.setText("Hasło:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 120, 40, 14);

        jLabel3.setText("Serwer:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 150, 50, 14);

        jLabel4.setText("Nazwa bazy danych:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 180, 110, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Logowanie do bazy danych...");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 18, 229, 22);

        jButton1.setText("Stwórz baze ...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(273, 255, 107, 23);
        getContentPane().add(portF);
        portF.setBounds(210, 210, 80, 30);

        jLabel6.setText("Port:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 210, 30, 14);

        boxIndex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TAK", "NIE" }));
        boxIndex.setSelectedIndex(1);
        boxIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIndexActionPerformed(evt);
            }
        });
        getContentPane().add(boxIndex);
        boxIndex.setBounds(210, 50, 60, 30);

        jLabel7.setText("Stworzyć nową bazę:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 50, 120, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background (1).png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(425, 310));
        jLabel8.setMinimumSize(new java.awt.Dimension(425, 310));
        jLabel8.setPreferredSize(new java.awt.Dimension(425, 310));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (index == 0) {
            System.out.println(index);
             DataBaseConnection data = new DataBaseConnection();
            try {
               
                bazalog.SetLog(logf.getText());
                bazalog.SetPas(hasf.getText());
                bazalog.SetServer(serverF.getText());

                bazalog.SetPort(Integer.parseInt(portF.getText()));
 System.out.println(logf.getText());
  System.out.println(hasf.getText());
                DataBaseConnection.s = "CREATE DATABASE " +bazaf.getText()+";" ;
                 System.out.println(bazalog.database);
                 data.Connection();
                System.out.println(DataBaseConnection.s);
                bazalog.SetDatabase(bazaf.getText());
                System.out.println(bazaf.getText());

                
           
               

                DataBaseConnection.s = "CREATE TABLE Logins\n"
                        + "(\n"
                        + "PESEL bigint,\n"
                        + "[Login] nchar(20),\n"
                        + "Hasło nchar(20),\n"
                        + "Typ nchar(20),\n"
                        + "PRIMARY KEY (PESEL)\n"
                        + ");\n"
                        + "CREATE TABLE Pacjen\n"
                        + "(\n"
                        + "PESEL bigint,\n"
                        + "Nazwisko nchar(20),\n"
                        + "Imie nchar(20),\n"
                        + "Wiek nchar(20),\n"
                        + "Płeć nchar(20),\n"
                        + "Token nchar(20),\n"
                        + "[Choroby Przewlekłe] nchar(200),\n"
                        + "PRIMARY KEY (PESEL)\n"
                        + ");\n"
                        + "CREATE TABLE Praco\n"
                        + "(\n"
                        + "PESEL bigint,\n"
                        + "Tytuł nchar(20),\n"
                        + "Stanowiko nchar(20),\n"
                        + "Token nchar(20),\n"
                        + "PRIMARY KEY (PESEL)\n"
                        + ");";
                data.Connection();
//////////////////////////////////////////////////////////////////////////////////////////////

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(bazacreator.class.getName()).log(Level.SEVERE, null, ex);

            }
            Log frame = new Log();
            frame.setVisible(true);
            this.setVisible(false);

        } else if (index == 1) {
             DataBaseConnection data = new DataBaseConnection();
            try {
                bazalog.SetDatabase(bazaf.getText());
                bazalog.SetLog(logf.getText());
                bazalog.SetPas(hasf.getText());
                bazalog.SetServer(serverF.getText());

                bazalog.SetPort(Integer.parseInt(portF.getText()));

                DataBaseConnection.s = "USE " + bazaf.getText();
               

                data.Connection();
                //////////////////////////////////////////////////////////////////
                

              
                data.Connection();
//////////////////////////////////////////////////////////////////////////////////////////////

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(bazacreator.class.getName()).log(Level.SEVERE, null, ex);

            }
            Log frame = new Log();
            frame.setVisible(true);
            this.setVisible(false);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIndexActionPerformed
        // TODO add your handling code here:
        index = boxIndex.getSelectedIndex();


    }//GEN-LAST:event_boxIndexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bazacreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bazacreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bazacreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bazacreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bazacreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bazaf;
    private javax.swing.JComboBox boxIndex;
    private javax.swing.JTextField hasf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField logf;
    private javax.swing.JTextField portF;
    private javax.swing.JTextField serverF;
    // End of variables declaration//GEN-END:variables
}
