/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Maciej
 */
public class Edyt extends javax.swing.JFrame {

    /**
     * Creates new form Edyt
     */
   DataBaseConnection bd = new DataBaseConnection();
  String tablicaInt[];
  String tablica[];
    public Edyt() {
        initComponents();
        
        
        
       
        
        
    }

    public void LoL() throws ClassNotFoundException{
    
    
        try{

         

            bd.setSql("SELECT PESEL FROM Pacjen");
     bd.Connection();
System.out.println("zapytanie#sql");
            ResultSet rs = bd.GetRS();
             tablica = new String[30];
            tablicaInt = new String[30];
            int licznik = 0;
            while (rs.next()) {
                String ID = rs.getString("PESEL");
                ID = ID.replace(" ", "");
                
System.out.println("dodano ID");
                

                tablicaInt[licznik] = ID;
                tablica[licznik] = ID;
                System.out.println("tablica[licznik]" + tablica[licznik]);
                licznik++;
            }
            PESELbox.setModel(new DefaultComboBoxModel(tablica));

        } catch (SQLException ex) {
          
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NazwiskoPole = new javax.swing.JTextField();
        ImiePole = new javax.swing.JTextField();
        WiekPole = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChorobaPole = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        PlecPole = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        PESELbox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 310));
        setMinimumSize(new java.awt.Dimension(610, 310));
        setPreferredSize(new java.awt.Dimension(610, 310));
        getContentPane().setLayout(null);

        NazwiskoPole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazwiskoPoleActionPerformed(evt);
            }
        });
        getContentPane().add(NazwiskoPole);
        NazwiskoPole.setBounds(240, 46, 87, 25);
        getContentPane().add(ImiePole);
        ImiePole.setBounds(240, 77, 90, 23);

        WiekPole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiekPoleActionPerformed(evt);
            }
        });
        getContentPane().add(WiekPole);
        WiekPole.setBounds(239, 106, 44, 25);

        jLabel5.setText("Płeć:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(203, 137, 32, 14);

        jLabel6.setText("Choroby:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 170, 59, 14);

        ChorobaPole.setColumns(20);
        ChorobaPole.setRows(5);
        jScrollPane1.setViewportView(ChorobaPole);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 170, 220, 100);

        jLabel2.setText("Nazwisko:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(178, 46, 58, 14);
        getContentPane().add(PlecPole);
        PlecPole.setBounds(239, 137, 72, 25);

        jLabel3.setText("Imię:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(204, 77, 32, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Edytowanie pacjenta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 180, 22);

        jLabel4.setText("Wiek:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 106, 35, 14);

        jButton1.setText("Uaktualnij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(476, 243, 100, 23);

        jLabel8.setText("Wybierz PESEL pacjenta do edycji:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 20, 210, 20);

        PESELbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PESELbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESELboxActionPerformed(evt);
            }
        });
        getContentPane().add(PESELbox);
        PESELbox.setBounds(340, 20, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazwiskoPoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazwiskoPoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NazwiskoPoleActionPerformed

    private void WiekPoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiekPoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WiekPoleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String pesel, nazw, imie, wiek, plec, chor;
            int indexpsel = PESELbox.getSelectedIndex();
             pesel = tablica[indexpsel];
            nazw = NazwiskoPole.getText();
            imie = ImiePole.getText();
            wiek = WiekPole.getText();
            plec = PlecPole.getText();
            chor = ChorobaPole.getText();
            DataBaseConnection data = new DataBaseConnection();
            DataBaseConnection.s = "UPDATE Pacjen SET Nazwisko='"+nazw+"',Imie='"+imie+"',Wiek='"+wiek+"',[Choroby Przewlekłe]='"+chor+"',Płeć='"+plec+"' WHERE PESEL="+pesel+"";
            try {
                data.Connection();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
            }
            Menu frame = new Menu();
            this.setVisible(false);

            frame.zaladuj();
            // frame.setVisible(false);
            frame.setVisible(true);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PESELboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESELboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PESELboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Edyt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ChorobaPole;
    private javax.swing.JTextField ImiePole;
    private javax.swing.JTextField NazwiskoPole;
    private javax.swing.JComboBox PESELbox;
    private javax.swing.JTextField PlecPole;
    private javax.swing.JTextField WiekPole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
