/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maciej
 */
public class Log extends javax.swing.JFrame {

    String luj;
    String luj1;
    String haslo;
    String login;

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        pasField = new javax.swing.JPasswordField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        BazaF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 250));
        setMinimumSize(new java.awt.Dimension(350, 250));
        setPreferredSize(new java.awt.Dimension(350, 250));
        getContentPane().setLayout(null);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 40, 14);
        getContentPane().add(loginField);
        loginField.setBounds(120, 60, 148, 30);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 60, 20);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 150, 47, 23);

        jToggleButton1.setText("Konfiguracja bazy");
        jToggleButton1.setActionCommand("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(30, 20, 140, 23);
        getContentPane().add(pasField);
        pasField.setBounds(120, 90, 148, 30);

        jToggleButton2.setText("Rejestracja ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(200, 20, 110, 23);

        jLabel3.setText("Baza:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 120, 40, 14);
        getContentPane().add(BazaF);
        BazaF.setBounds(120, 120, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background (1).png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(350, 250));
        jLabel4.setMinimumSize(new java.awt.Dimension(350, 250));
        jLabel4.setPreferredSize(new java.awt.Dimension(350, 250));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 340, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        bazalog.SetDatabase(BazaF.getText());
        haslo = pasField.getText();
        login = loginField.getText();
             System.out.println(haslo+"lll");
             DataBaseConnection data = new DataBaseConnection();
        if (haslo.equals("admin1")) {
            try {
                
                DataBaseConnection.s = "select * from Pacjen";

                Menu frame = new Menu();
                frame.zaladuj();

                frame.setVisible(true);
                this.setVisible(false);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Log.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        try {
            

            System.out.println(pasField.getText());

            DataBaseConnection.s = "SELECT TOP 1 Hasło FROM Logins WHERE Login='" + login + "'";
            System.out.println(DataBaseConnection.s);
            data.Connection();
            ResultSet te = data.GetRS();
            luj = "";

            if (te.next()) {
                luj = te.getString("Hasło");
                luj = luj.replace(" ", "");
            }
            System.out.println(luj);
            System.out.println(haslo);
            if (luj.equals(haslo)) {

                DataBaseConnection.s = "SELECT TOP 1 Typ FROM Logins WHERE Login='" + login + "'";
                System.out.println(luj);
                String typ1 = "1";
                String typ2 = "0";
                data.Connection();
                ResultSet te1 = data.GetRS();
                luj1 = "";
                luj1 = luj1.replace(" ", "");
                if (te1.next()) {
                    luj1 = te1.getString("Typ");
                    luj1 = luj1.replace(" ", "");
                }
                System.out.println(luj1 + "__________________________");
                if (typ2.equals(luj1)) {
                    System.out.println(luj1 + "__________________________");
                    DataBaseConnection.s = "select * from Pacjen";

                    Menu frame = new Menu();
                    frame.zaladuj();

                    frame.setVisible(true);
                    this.setVisible(false);

                }
                if (typ1.equals(luj1)) {
                    System.out.println(luj1 + "__________________333______");
                    Loging.SetLog(login);
                    Pacjent frame1 = new Pacjent();
                    frame1.zaladuj();

                    frame1.setVisible(true);
                    this.setVisible(false);

                }

            } else {
                System.out.println("WTF");
               
       
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Log.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Log.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        bazacreator frame = new bazacreator();
        frame.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
         Reje frame = new Reje();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BazaF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField loginField;
    private javax.swing.JPasswordField pasField;
    // End of variables declaration//GEN-END:variables
}
