/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maciej
 */
public class Reje extends javax.swing.JFrame {

    
   
    /**
     * Creates new form Reje
     */
    String luj;

    public Reje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        peselF = new javax.swing.JTextField();
        TokenF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HasloF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        typbox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        bazaF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel1.setText("PESEL:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 50, 14);

        peselF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peselFActionPerformed(evt);
            }
        });
        getContentPane().add(peselF);
        peselF.setBounds(140, 90, 100, 30);
        getContentPane().add(TokenF);
        TokenF.setBounds(140, 120, 60, 30);

        jLabel3.setText("Token:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 120, 40, 14);

        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 150, 40, 14);

        LoginF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFActionPerformed(evt);
            }
        });
        getContentPane().add(LoginF);
        LoginF.setBounds(140, 150, 110, 30);

        jLabel4.setText("Hasło:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 180, 40, 14);
        getContentPane().add(HasloF);
        HasloF.setBounds(140, 180, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Rejestracja");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 5, 116, 33);

        jButton1.setText("Rejestruj...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 260, 89, 23);

        typbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "lekarz", "pacjent" }));
        typbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typboxActionPerformed(evt);
            }
        });
        getContentPane().add(typbox);
        typbox.setBounds(140, 60, 70, 30);

        jLabel6.setText("Typ:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 60, 30, 14);

        bazaF.setText("jTextField1");
        bazaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaFActionPerformed(evt);
            }
        });
        getContentPane().add(bazaF);
        bazaF.setBounds(140, 210, 110, 30);

        jLabel8.setText("Baza:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 50, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background (1).png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(400, 403));
        jLabel7.setMinimumSize(new java.awt.Dimension(400, 403));
        jLabel7.setPreferredSize(new java.awt.Dimension(400, 403));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginFActionPerformed

    private void peselFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peselFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peselFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
             bazalog.SetDatabase(bazaF.getText());
            Loging.SetLog("admin");
            Loging.SetPas("admin1");

            // TODO add your handling code here:
            DataBaseConnection data = new DataBaseConnection();
            String pesel, token, login, haslo, peselcheck;
            int index = typbox.getSelectedIndex();
            System.out.println(index);
            pesel = peselF.getText();
            token = TokenF.getText();
            login = LoginF.getText();
            haslo = HasloF.getText();

            if (index == 1) {
                DataBaseConnection.s = "SELECT PESEL FROM Pacjen WHERE Token='" + token + "'";
                System.out.println(DataBaseConnection.s);
                data.Connection();
                ResultSet te = data.GetRS();
                luj = "";
                luj = luj.replace(" ", "");
                if (te.next()) {
                    luj = te.getString("PESEL");
                }
                System.out.println(luj);
                if (pesel.equals(luj)) {

                    DataBaseConnection.s = "INSERT INTO Logins (PESEL, Hasło, Typ, [Login]) VALUES ( '" + pesel + "','" + haslo + "', '" + index + "', '" + login + "')";
                    try {
                        data.Connection();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Log frame = new Log();
                    this.setVisible(false);

                    // frame.setVisible(false);
                    frame.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(null, "Zły token lub baza nie odpowiada ", "Error",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
            if (index == 0) {

                DataBaseConnection.s = "SELECT PESEL FROM Pacjen WHERE Token='" + token + "'";
                System.out.println(DataBaseConnection.s);
                data.Connection();
                ResultSet te = data.GetRS();
                luj = "";
                luj = luj.replace(" ", "");
                if (te.next()) {
                    luj = te.getString("PESEL");
                }
                System.out.println(luj);
                if (pesel.equals(luj)) {

                    DataBaseConnection.s = "INSERT INTO Logins (PESEL, Hasło, Typ, [Login]) VALUES ( '" + pesel + "','" + haslo + "', '" + index + "', '" + login + "')";
                    try {
                        data.Connection();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Log frame = new Log();
                    this.setVisible(false);

                    // frame.setVisible(false);
                    frame.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(null, "Zły token lub baza nie odpowiada ", "Error",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
            //DataBaseConnection.s = "INSERT INTO Loginy (PESEL, Token, Imie, Login, Haslo, [Choroby Przewlekłe],Token) VALUES (" + pesel + ", '" + nazw + "', '" + imie + "', '" + wiek + "','" + plec + "', '" + chor + "', '" + token + "')";
            try {
                data.Connection();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
            }
            Menu frame = new Menu();
            this.setVisible(false);

            try {
                frame.zaladuj();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reje.class.getName()).log(Level.SEVERE, null, ex);
            }
            // frame.setVisible(false);
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void typboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typboxActionPerformed

    private void bazaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bazaFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField HasloF;
    private javax.swing.JTextField LoginF;
    private javax.swing.JTextField TokenF;
    private javax.swing.JTextField bazaF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField peselF;
    private javax.swing.JComboBox typbox;
    // End of variables declaration//GEN-END:variables
}
