/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanager;

import static hospitalmanager.Menu.buildTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maciej
 */
public class Szuk extends javax.swing.JFrame {

    /**
     * Creates new form Szuk
     */
    public Szuk() {
        initComponents();
    }
    public void zaladuj() throws ClassNotFoundException {
        try {
            
            DataBaseConnection data = new DataBaseConnection();

            data.Connection();

            Tabela.setModel(buildTableModel(data.GetRS()));
            Tabela.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        peselField = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        ExitB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(520, 300));
        setMinimumSize(new java.awt.Dimension(520, 300));
        setPreferredSize(new java.awt.Dimension(520, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("PESEL:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 60, 50, 20);

        peselField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peselFieldActionPerformed(evt);
            }
        });
        getContentPane().add(peselField);
        peselField.setBounds(204, 63, 150, 30);

        jToggleButton1.setText("Szukaj");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(240, 100, 80, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Szukanie pacjenta:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 233, 36);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(8, 196, 490, 50);

        ExitB.setText("EXIT");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });
        getContentPane().add(ExitB);
        ExitB.setBounds(430, 10, 70, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peselFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peselFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peselFieldActionPerformed

   
     
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            // TODO add your handling code here:

            String pesel;
            pesel = peselField.getText();
            

            DataBaseConnection data = new DataBaseConnection();
            DataBaseConnection.s = "USE "+bazalog.database+" SELECT [PESEL],[Nazwisko],[Imie],[Wiek],[Choroby Przewlekłe],[Płeć] FROM ["+bazalog.database+"].[dbo].[Pacjen] WHERE PESEL="+pesel+"";
             data.Connection();
             zaladuj();
            try {
                data.Connection();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dodaj.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            zaladuj();
            // frame.setVisible(false);
           

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usun.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitB;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField peselField;
    // End of variables declaration//GEN-END:variables
}
